import { promises as fs } from 'node:fs';
import { join } from 'node:path';
import {
	CONCURRENCY,
	DIST_DIR,
	ensureIconsPackage,
	exists,
	pool,
	readVariantJobs,
	VARIANTS
} from './shared.mjs';

const FORCE = process.argv.includes('--force');

function svelteTemplate(viewBox, title, body) {
	return `<script lang="ts">
  // This file is auto-generated. Do not edit manually.
  // Generated from the official Material Design Icons by Google.
  // https://fonts.google.com/icons

	import type { SvelteHTMLElements } from 'svelte/elements';

	type Props = {
		[K in keyof SvelteHTMLElements['svg']]: SvelteHTMLElements['svg'][K];
	};

	let {
		width = '1em',
		height = '1em',
		...restProps
	}: Props = $props();
</script>

<svg
	xmlns="http://www.w3.org/2000/svg"
	{width}
	{height}
	viewBox="${viewBox}"
	fill="currentColor"
	stroke="currentColor"
	{...restProps}
>
	<title>${title.replace(/(^|\s)([a-z])/g, (_, space, char) => `${space}${char.toUpperCase()}`)}</title>
	${body}
</svg>

<style>

svg {
	display: inline-block;
	stroke-width: 0px;
}

</style>
`;
}

function componentTypesTemplate(componentName) {
	return `/** @generated by Svelte */
import type { Component } from 'svelte';
import type { SvelteHTMLElements } from 'svelte/elements';

type Props = {
	[K in keyof SvelteHTMLElements['svg']]: SvelteHTMLElements['svg'][K];
};

declare const ${componentName}: Component<Props>;

export default ${componentName};
`;
}

await ensureIconsPackage();
await fs.mkdir(DIST_DIR, { recursive: true });

let generated = 0;
let skipped = 0;

for (const variant of VARIANTS) {
	const variantDir = join(DIST_DIR, variant);

	if (!FORCE && (await exists(variantDir))) {
		console.log(`Skipping "${variant}" (already generated, run with --force to regenerate)`);
		skipped++;
		continue;
	}

	const tmpDir = `${variantDir}.tmp`;

	try {
		await fs.rm(tmpDir, { recursive: true, force: true });
		await fs.mkdir(tmpDir, { recursive: true });

		const jobs = await readVariantJobs(variant);

		await pool(jobs, CONCURRENCY, async (job) => {
			await Promise.all([
				fs.writeFile(
					join(tmpDir, `${job.componentName}.svelte`),
					svelteTemplate(job.viewBox, job.title, job.body)
				),
				fs.writeFile(
					join(tmpDir, `${job.componentName}.svelte.d.ts`),
					componentTypesTemplate(job.componentName)
				)
			]);
		});

		const barrel = jobs.map(
			(job) => `export { default as ${job.componentName} } from './${job.componentName}.svelte';`
		);

		await Promise.all([
			fs.writeFile(join(tmpDir, 'index.js'), `${barrel.join('\n')}\n`),
			fs.writeFile(join(tmpDir, 'index.d.ts'), `${barrel.join('\n')}\n`)
		]);

		await fs.rm(variantDir, { recursive: true, force: true });
		await fs.rename(tmpDir, variantDir);

		console.log(`Generated ${jobs.length} icons in "${variant}"`);
		generated++;
	} catch (error) {
		await fs.rm(tmpDir, { recursive: true, force: true });
		await fs.rm(variantDir, { recursive: true, force: true });

		console.error(`Failed to generate "${variant}", its folder was removed.`);
		throw error;
	}
}

console.log(`Done. ${generated} generated, ${skipped} skipped.`);
